---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - frontend/overlays/non-prod
  - pgadmin/overlays/non-prod
  - postgres/overlays/non-prod
  - backend/overlays/non-prod
