---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: gofiber
    app.kubernetes.io/name: gofiber
  name: gofiber
  namespace: default
spec:
  selector:
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: gofiber
    app.kubernetes.io/name: gofiber
  # type: ClusterIP
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 5000
      nodePort: 30300
      # targetPort: http
