---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: pgadmin
    app.kubernetes.io/name: pgadmin
data:
  PGADMIN_DEFAULT_EMAIL: "user@domain.com"
  PGADMIN_DEFAULT_PASSWORD: "admin"
  PGADMIN_PORT: "80"
