apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: pgadmin
    app.kubernetes.io/name: pgadmin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: database
      app.kubernetes.io/instance: pgadmin
      app.kubernetes.io/name: pgadmin
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: database
        app.kubernetes.io/instance: pgadmin
        app.kubernetes.io/name: pgadmin
    spec:
      containers:
        - name: pgadmin4
          image: dpage/pgadmin4
          imagePullPolicy: "IfNotPresent"
          envFrom:
            - configMapRef:
                name: pgadmin-config
          ports:
            - containerPort: 80
              name: pgadminport
