version: "3.8"
services:
  postgres:
    image: postgres:11-alpine
    restart: always
    environment: 
      POSTGRES_PASSWORD: rocket
      POSTGRES_USER: rocket
      POSTGRES_DB: rocket
    #INFO: reminder host:container
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
