---
# https://kubernetes.io/docs/concepts/configuration/configmap/
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: svelte
    app.kubernetes.io/name: svelte
  name: frontend-config
  namespace: default
data:
  key: value
