apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-crds
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: monitoring
  source:
    repoURL: https://github.com/prometheus-community/helm-charts.git
    path: charts/kube-prometheus-stack/crds/
    targetRevision: kube-prometheus-stack-39.9.0
    directory:
      recurse: true
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - Replace=true
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  labels:
    app.kubernetes.io/instance: application-of-applications
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: monitoring
  source:
    path: k8s/charts/prometheus-grafana
    repoURL: git@github.com:Vanderscycle/Professional-website.git
    targetRevision: main
    helm:
      releaseName: monitoring
      skipCrds: true
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
