upstream django {
    server django_gunicorn:8000;
}


server {
    listen 80;
    server_name neuraldomains.com www.neuraldomains.com localhost 127.0.0.1 172.105.7.38;
    location = /favicon.ico { access_log off; log_not_found off; }
    location / {
        proxy_pass http://django;
    }

    location /static/ {
        alias /collected_static/;
    }
    location /media/ {
        alias /media/;
    }
}