resources:
  - ../../base

patches:
  - patch: |-
      - op: add
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
        value: "letsencrypt-cluster-issuer-prod"
    target:
      kind: Ingress
      name: professional-web-frontend
