apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: security
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: My infrastructure security
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  destinations:
    - namespace: vault
      server: https://kubernetes.default.svc
    - namespace: consul
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc

  sourceRepos:
    - git@github.com:Vanderscycle/Professional-website.git

    - https://helm.releases.hashicorp.com
      # hashicorp vault
    - https://github.com/hashicorp/vault
    - https://github.com/hashicorp/vault-helm
    - https://github.com/hashicorp/vault-k8s
    - https://github.com/hashicorp/vault-csi-provider
      # hashicorp consul
    - https://github.com/hashicorp/consul
    - https://github.com/hashicorp/consul-k8s
