---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: website
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Henri Vandersleyen Professional website
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"

  destinations:
    - namespace: website
      server: https://kubernetes.default.svc
  sourceRepos:
    - git@github.com:Vanderscycle/Professional-website.git
    # - https://github.com/Vanderscycle/Professional-website.git
