---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: website
  namespace: default
spec:
  selector:
    app: website
  type: ClusterIP
  ports:
    - name: website
      protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001
---
