---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-website
  namespace: argocd
  # don't enable finalizer otherwise it'll cause a cascading delete of projects if this app is removed
  #finalizers:
  #  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:Vanderscycle/Professional-website.git
    targetRevision: main
    path: argocd/apps/website
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
