---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-security
  namespace: argocd
  labels:
    app.kubernetes.io/instance: application-of-applications
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: k8s/argocd/apps/security
    repoURL: git@github.com:Vanderscycle/Professional-website.git
    # repoURL: https://github.com/Vanderscycle/Professional-website.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
