---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-root
  namespace: argocd
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: applications
  source:
    path: k8s/argocd/
    repoURL: git@github.com:Vanderscycle/Professional-website.git
    # repoURL: https://github.com/Vanderscycle/Professional-website.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
