# https://kubernetes.io/docs/concepts/configuration/configmap/
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: gofiber
    app.kubernetes.io/name: gofiber
    app.kubernetes.io/part-of: professional-website
  name: gofiber-config
data:
  POSTGRES_DB: postgresdb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: root
  POSTGRES_PORT: "5432"
  POSTGRES_HOST: "localhost"
