---
kind: Namespace
apiVersion: v1
metadata:
  name: postgres
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: professional-website
  namespace: website
