---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgres
spec:
  selector:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgres
  type: NodePort
  ports:
  - name: postgres
    port: 5432
    nodePort: 30432
