---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: professional-website
spec:
  selector:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgres
  # type: ClusterIP
  type: NodePort
  ports:
    - name: http
      port: 5432
      protocol: TCP
      targetPort: http
      # nodePort: 30432
---
apiVersion: v1
kind: Endpoints
metadata:
  name: postgres-service
subsets:
  - addresses:
      - ip: 107.190.16.28
    ports:
      - port: 5432
