---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: professional-website
spec:
  selector:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgres
  type: NodePort
  ports:
    - name: http
      port: 5432
      protocol: TCP
      targetPort: http
      # nodePort: 30432
