---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./frontend/overlays/non-prod
  - ./pgadmin/overlays/non-prod
  - ./postgres/overlays/non-prod
  - ./backend/overlays/non-prod
  # - ./cert-manager/overlays/non-prod
patches:
  - target:
      kind: Deployment
      name: frontend
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
  - target:
      kind: Deployment
      name: gofiber
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
