---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hashicorp-consul
  labels:
    app.kubernetes.io/instance: application-of-applications
spec:
  destination:
    namespace: consul
    server: https://kubernetes.default.svc
  project: security
  source:
    path: k8s/charts/hashicorp-consul
    repoURL: git@github.com:Vanderscycle/Professional-website.git
    targetRevision: main
    helm:
      releaseName: security
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
