# https://kubernetes.io/docs/concepts/configuration/configmap/
kind: ConfigMap
apiVersion: v1
metadata:
  name: argocd-secret-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repository: |
    - url: git@github.com:Vanderscycle/Professional-website.git
      sshPrivateKeySecret:
        name: argocd-secret
        key: privateKey
