apiVersion: v1
kind: Secret
metadata:
  name: main-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  name: professional-website
  url: git@github.com:Vanderscycle/Professional-website.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    -----END OPENSSH PRIVATE KEY-----
