apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: professional-website-tls
spec:
  dnsNames:
    - me.vandersleyen.dev
  secretName: professional-website-tls
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-cluster-issuer-non-prod
