on:
  workflow_call:
    inputs:
      deploy_image:
        required: true
        type: boolean

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    if: inputs.deploy_image
    steps:
      - uses: actions/checkout@v3
      - name: Login docker hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          docker login -u "$DOCKER_USER" --password "$DOCKER_PASSWORD"

      - name: Build Docker image
        run: |
          (cd ./frontend && docker build . --tag vandercycle/professional-website:latest)

      - name: Docker Push image
        run: |
          docker push vandercycle/professional-website:latest