on:
  workflow_call:
    inputs:
      deploy_image:
        required: true
        type: boolean

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    if: inputs.deploy_image
    steps:
      - uses: actions/checkout@v3
      - name: Login docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: |
          (cd ./frontend && docker build . --tag vandercycle/professional-website:latest)

      - name: Docker Push image
        run: |
          docker push vandercycle/professional-website:latest