---
name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login docker hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          docker login -u "$DOCKER_USER" --password "$DOCKER_PASSWORD"

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      #   with:
      #     images: my-docker-hub-namespace/my-docker-hub-repository

      # - name: Build and push Docker image
      #   uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      #   with:
      #     context: .
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}

# jobs:
#   release:
#     name: release images to dockerhub
#     runs-on: ubuntu-latest

#     steps:
#       # - name: Set up QEMU
#       #   uses: docker/setup-qemu-action@v2
#       # - name: Set up Docker Buildx
#       #   uses: docker/setup-buildx-action@v2
#       - name: Login to Docker Hub
#         uses: docker/build-push-action@v2
#         with:
#           username: ${{ secrets.DOCKER_HUB_USERNAME }}
#           password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#         # env:
#         #   DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
#         #   DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

#       - name: Build Docker image
#         # uses: docker/build-push-action@v3
#         run: |
#           docker build "$PWD"/backend --file Dockerfile --tag vandercycle/professional-website-backend:latest
#           docker build "$PWD"/frontend --file Dockerfile --tag vandercycle/professional-website:latest

#       - name: Docker Push image
#         run: |
#           docker push vandercycle/professional-website-backend:latest
#           docker push vandercycle/professional-website:latest
