name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  release:
    name: release images to dockerhub
    runs-on: ubuntu-latest
    # environment: Production

    steps:
      # - name: test
      #   shell: bash
      #   run: echo "$DOCKER_USER"
      #   env:
      #     DOCKER_USER: "bro"

      - name: Logout from Docker Hub
        if: always()
        run: docker logout

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }}
          -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # - name: Login into Docker
      #   uses: docker/login-action@v2
      #   # with:
      #   #   username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #   #   password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      #   env:
      #     DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
      #     DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      #   with:
      #     username: $DOCKER_USER
      #     password: $DOCKER_PASSWORD
      # run: |
      #   echo $DOCKER_USER $DOCKER_PASSWORD

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        # uses: docker/build-push-action@v2
        run: |
          docker build ./backend --file Dockerfile --tag vandercycle/professional-website-backend:latest
          docker build ./frontend --file Dockerfile --tag vandercycle/professional-website:latest

      - name: Docker Push image
        run: |
          docker push vandercycle/professional-website-backend:latest
          docker push vandercycle/professional-website:latest
