---
name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Login docker hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          docker login -u "$DOCKER_USER" --password "$DOCKER_PASSWORD"

      - name: Build Docker image
        uses: actions/checkout@v3
        run: |
          docker build ./backend --file Dockerfile --tag vandercycle/professional-website-backend:latest
          docker build ./frontend --file Dockerfile --tag vandercycle/professional-website:latest

      - name: Docker Push image
        run: |
          docker push vandercycle/professional-website-backend:latest
          docker push vandercycle/professional-website:latest
