name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  release:
    name: release images to dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build the backend Docker image
        run: docker build ./backend --file Dockerfile --tag vandercycle/professional-website-backend:latest

      - name: Docker Push backend image
        run: docker push vandercycle/professional-website-backend:latest

      - name: Build the frontend Docker image
        run: docker build ./frontend --file Dockerfile --tag vandercycle/professional-website:latest

      - name: Docker Push frontend image
        run: docker push vandercycle/professional-website:latest
