name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  release:
    name: release images to dockerhub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Logout from Docker Hub
      #   if: always()
      #   run: docker logout

      - name: Login to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        # env:
        #   DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
        #   DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: |
          docker build "$PWD"/backend --file Dockerfile --tag vandercycle/professional-website-backend:latest
          docker build "$PWD"/frontend --file Dockerfile --tag vandercycle/professional-website:latest

      - name: Docker Push image
        run: |
          docker push vandercycle/professional-website-backend:latest
          docker push vandercycle/professional-website:latest
