name: 'Pipeline: Non-prod'
on:
  push:
    # branches:
    #   - '*'
  workflow_dispatch:
    inputs:
      deploy_image:
        required: true
        type: boolean

jobs:
  docker:
    uses: './.github/workflows/_pipeline.yml'
    secrets: inherit
    with:
      deploy_image: ${{ inputs.deploy_image || true }}