name: 'Pipeline: Non-prod'
on:
  push:
    # branches:
    #   - '*'
  workflow_dispatch:
    inputs:
      deploy_image:
        required: true
        type: boolean

jobs:
  build-and-push:
    uses: ./.github/actions/docker-build-push
    with:
      context: './frontend'
      dockerfile: './frontend/Dockerfile'
      image_name: 'professional-website'
    secrets:
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_hub_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
