name: 'Pipeline: Non-prod'
on:
  push:
    # branches:
    #   - '*'
  workflow_dispatch:
    inputs:
      deploy_image:
        required: true
        type: boolean

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and Push Docker Image
        uses: Vanderscycle/pipelines/dockerhub@main
        with:
          context: './frontend'
          dockerfile: './frontend/Dockerfile'
          image_name: 'professional-website'
        # secrets:
          docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
          docker_hub_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
