apiVersion: v2
name: vault
version: 0.21.0
appVersion: 1.11.2
description: Official HashiCorp Vault Chart
home: https://www.vaultproject.io
icon: https://github.com/hashicorp/vault/raw/f22d202cde2018f9455dec755118a9b84586e082/Vault_PrimaryLogo_Black.png

sources:
  - https://github.com/hashicorp/vault
  - https://github.com/hashicorp/vault-helm
  - https://github.com/hashicorp/vault-k8s
  - https://github.com/hashicorp/vault-csi-provider
dependencies:
  - name: vault
    repository: https://artifacthub.io/packages/helm/hashicorp/vault
    version: 0.21.0
